### ISSUE TITLE
Publish for Scala 2.13

### ISSUE THREAD

**Issue by aeons** [reactormonk/cryptobits#11]
Would be nice to have 1.2 for Scala 2.13

**Comment by reactormonk** [comment]
[error] java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/org/reactormonk/cryptobits_2.11/1.2/cryptobits_2.11-1.2-sources.jar was refused by the server: Unauthorized

sonatype doesn't like me anymore. I submitted the correct credentials according to https://my.sonatype.com/

**Comment by reactormonk** [comment]
> Li Haoyi @lihaoyi 11:33
> use Mill
> publishing just works

But I'm a bit lazy on the migration.

**Comment by aeons** [comment]
Yay, publishing scala libraries! :D

**Comment by reactormonk** [comment]
> Published cryptobits_2.13, cryptobits_2.12, cryptobits_2.11, cryptobits_2.10 successfully

Should be on its way to maven central. Thanks for the help.

**Comment by aeons** [comment]
Great, thanks.
